// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ReimbursementController from "./reimbursement_controller"
application.register("reimbursement", ReimbursementController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)
